name: 'Test action'
description: 'Test action'
author: 'Juraj Piar'
inputs:
  github_token:
    description: Token for the GitHub API.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
