name: Sync github push gha metrics source

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *" # Runs every hour

jobs:
  update-version:
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Update Version
        continue-on-error: true

      - name: Checkout the repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Update version
        env:
          GH_TOKEN: ${{ secrets.GHA_ACTIONS_SOURCE_PULL_TOKEN }}
        run: ./sync-from-source/sync.sh

      - name: Open PR
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          title: Update push-gha-metrics-action
          branch: chore/update-push-gha-metrics-action
          commit-message: Update push-gha-metrics-action